### ISSUE TITLE
Error after npm install

### ISSUE THREAD

**Issue by BillMeyerRSA** [wmfs/tymly#454]
After npm install @wmfs/tymly-cli -g, any tymly shell command gives error.
Any idea what it can be?
$ tymly init
/usr/lib/node_modules/@wmfs/tymly-cli/lib/actions/add-model/index.js:74
  for await (const property of gatherModelProperty(dataDomains)) {
      ^^^^^

SyntaxError: Unexpected reserved word
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/@wmfs/tymly-cli/lib/actions/index.js:6:19)

**Comment by jezhiggins** [comment]
for await ... of creates a loop operating over asynchronous iterator objects. It was introduced in ES 2018 and is supported in Node 10 and upwards. I suspect you're running an earlier version of Node. If it's 9.2 or higher, you can pass the --harmony-async-iteration to enable this feature, otherwise you'll need to update your Node installation.

**Comment by BillMeyerRSA** [comment]
Was on Ubuntu 18.04 server. Tried on another Ubuntu server, same problem.
Loaded on a Debian 10 server, clean install, no problem. 
On all it had latest Node version. 
Must be some Node modules that was loaded that is not present on a clean install.
